import '../models/recipe.dart';

final List<Recipe> dummyRecipes = [
  Recipe(
    id: '1',
    title: 'Creamy Garlic Parmesan Pasta',
    description: 'A delicious and creamy pasta dish loaded with garlic and parmesan cheese. Perfect for a quick weeknight dinner that the whole family will love!',
    imageUrl: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?q=80&w=1170&auto=format&fit=crop',
    ingredients: [
      {'name': 'Fettuccine pasta', 'amount': '12', 'unit': 'oz'},
      {'name': 'Butter', 'amount': '4', 'unit': 'tbsp'},
      {'name': 'Garlic', 'amount': '4', 'unit': 'cloves, minced'},
      {'name': 'Heavy cream', 'amount': '1', 'unit': 'cup'},
      {'name': 'Parmesan cheese', 'amount': '1', 'unit': 'cup, grated'},
      {'name': 'Salt', 'amount': '1/2', 'unit': 'tsp'},
      {'name': 'Black pepper', 'amount': '1/4', 'unit': 'tsp'},
      {'name': 'Fresh parsley', 'amount': '2', 'unit': 'tbsp, chopped'},
    ],
    instructions: [
      'Cook pasta according to package directions until al dente. Reserve 1/2 cup pasta water before draining.',
      'While pasta cooks, melt butter in a large skillet over medium heat. Add minced garlic and sauté for 1-2 minutes until fragrant.',
      'Reduce heat to medium-low and add heavy cream. Simmer for 3-4 minutes until it starts to thicken slightly.',
      'Stir in the grated parmesan cheese until melted and smooth. Season with salt and pepper.',
      'Add the drained pasta to the sauce and toss to coat. If needed, add reserved pasta water a little at a time to reach desired consistency.',
      'Garnish with chopped parsley and additional parmesan if desired. Serve immediately.'
    ],
    totalTimeMinutes: 25,
    category: 'Dinner',
    rating: 4.8,
    isFavorite: true,
    difficulty: 'Easy',
    servings: 4,
    calories: 620,
    chefName: 'Chef Emma',
    aiTips: 'For extra flavor, try adding a pinch of red pepper flakes or a splash of white wine to the sauce. You can also substitute half and half for heavy cream for a lighter version.',
    prepTimeMinutes: 10,
  ),
  Recipe(
    id: '2',
    title: 'Crispy Baked Chicken Thighs',
    description: 'Juicy chicken thighs with perfectly crispy skin, seasoned with herbs and spices. This easy recipe requires minimal prep and delivers maximum flavor!',
    imageUrl: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?q=80&w=1170&auto=format&fit=crop',
    ingredients: [
      {'name': 'Chicken thighs', 'amount': '8', 'unit': 'bone-in, skin-on'},
      {'name': 'Olive oil', 'amount': '2', 'unit': 'tbsp'},
      {'name': 'Paprika', 'amount': '1', 'unit': 'tbsp'},
      {'name': 'Garlic powder', 'amount': '1', 'unit': 'tsp'},
      {'name': 'Onion powder', 'amount': '1', 'unit': 'tsp'},
      {'name': 'Dried thyme', 'amount': '1', 'unit': 'tsp'},
      {'name': 'Salt', 'amount': '1', 'unit': 'tsp'},
      {'name': 'Black pepper', 'amount': '1/2', 'unit': 'tsp'},
    ],
    instructions: [
      'Preheat oven to 425°F (220°C) and line a baking sheet with foil or parchment paper.',
      'Pat chicken thighs dry with paper towels. This helps achieve crispy skin.',
      'In a small bowl, mix together paprika, garlic powder, onion powder, thyme, salt, and pepper.',
      'Brush chicken thighs with olive oil, then generously rub with the spice mixture on both sides.',
      'Place chicken thighs skin-side up on the prepared baking sheet, leaving space between each piece.',
      'Bake for 35-40 minutes, or until skin is crispy and golden, and internal temperature reaches 165°F (74°C).',
      'Let rest for 5 minutes before serving to allow juices to redistribute.'
    ],
    totalTimeMinutes: 45,
    category: 'Dinner',
    rating: 4.9,
    isFavorite: false,
    difficulty: 'Easy',
    servings: 4,
    calories: 350,
    chefName: 'Chef Michael',
    aiTips: 'For even crispier skin, broil the chicken for the last 2-3 minutes, watching carefully to prevent burning. You can also add different herbs like rosemary or oregano to customize the flavor profile.',
    prepTimeMinutes: 10,
  ),
  Recipe(
    id: '3',
    title: 'Classic Greek Salad',
    description: 'Fresh, vibrant, and packed with Mediterranean flavors, this traditional Greek salad combines crisp vegetables, tangy feta, and a simple olive oil dressing.',
    imageUrl: 'https://images.unsplash.com/photo-1551248429-40975aa4de74?q=80&w=1170&auto=format&fit=crop',
    ingredients: [
      {'name': 'Cucumber', 'amount': '1', 'unit': 'large, diced'},
      {'name': 'Tomatoes', 'amount': '4', 'unit': 'medium, cut into wedges'},
      {'name': 'Red onion', 'amount': '1/2', 'unit': 'thinly sliced'},
      {'name': 'Green bell pepper', 'amount': '1', 'unit': 'diced'},
      {'name': 'Kalamata olives', 'amount': '1/2', 'unit': 'cup'},
      {'name': 'Feta cheese', 'amount': '200', 'unit': 'g, cubed'},
      {'name': 'Extra virgin olive oil', 'amount': '1/4', 'unit': 'cup'},
      {'name': 'Red wine vinegar', 'amount': '2', 'unit': 'tbsp'},
      {'name': 'Dried oregano', 'amount': '1', 'unit': 'tsp'},
      {'name': 'Salt and pepper', 'amount': '', 'unit': 'to taste'},
    ],
    instructions: [
      'Combine cucumber, tomatoes, red onion, bell pepper, and olives in a large bowl.',
      'In a small bowl, whisk together olive oil, red wine vinegar, oregano, salt, and pepper to make the dressing.',
      'Pour the dressing over the vegetables and toss gently to combine.',
      'Place the cubed feta cheese on top of the salad.',
      'Sprinkle with a little more oregano and serve immediately for maximum freshness.'
    ],
    totalTimeMinutes: 15,
    category: 'Side Dish',
    rating: 4.7,
    isFavorite: true,
    difficulty: 'Easy',
    servings: 4,
    calories: 220,
    chefName: 'Chef Sophia',
    aiTips: 'For authentic Greek flavor, use high-quality feta packed in brine rather than pre-crumbled varieties. Let the salad rest for 10 minutes before serving to allow flavors to meld together.',
    prepTimeMinutes: 15,
  ),
  Recipe(
    id: '4',
    title: 'Fluffy Blueberry Pancakes',
    description: 'Start your morning with these light and fluffy pancakes studded with juicy blueberries. Drizzle with maple syrup for the perfect weekend breakfast!',
    imageUrl: 'https://images.unsplash.com/photo-1558401552-2e247774bd18?q=80&w=1170&auto=format&fit=crop',
    ingredients: [
      {'name': 'All-purpose flour', 'amount': '2', 'unit': 'cups'},
      {'name': 'Baking powder', 'amount': '2', 'unit': 'tsp'},
      {'name': 'Baking soda', 'amount': '1/2', 'unit': 'tsp'},
      {'name': 'Salt', 'amount': '1/4', 'unit': 'tsp'},
      {'name': 'Sugar', 'amount': '3', 'unit': 'tbsp'},
      {'name': 'Eggs', 'amount': '2', 'unit': 'large'},
      {'name': 'Buttermilk', 'amount': '2', 'unit': 'cups'},
      {'name': 'Vanilla extract', 'amount': '1', 'unit': 'tsp'},
      {'name': 'Butter', 'amount': '3', 'unit': 'tbsp, melted'},
      {'name': 'Fresh blueberries', 'amount': '1 1/2', 'unit': 'cups'},
      {'name': 'Maple syrup', 'amount': '', 'unit': 'for serving'},
    ],
    instructions: [
      'In a large bowl, whisk together flour, baking powder, baking soda, salt, and sugar.',
      'In another bowl, whisk eggs, then add buttermilk, vanilla, and melted butter.',
      'Pour the wet ingredients into the dry ingredients and stir just until combined. Do not overmix - some lumps are fine.',
      'Gently fold in 1 cup of the blueberries.',
      'Heat a griddle or skillet over medium heat and lightly grease.',
      'Scoop about 1/4 cup of batter for each pancake onto the hot griddle.',
      'Sprinkle a few of the remaining blueberries on top of each pancake.',
      'Cook until bubbles form on the surface, then flip and cook until golden brown, about 2-3 minutes per side.',
      'Serve warm with maple syrup.'
    ],
    totalTimeMinutes: 30,
    category: 'Breakfast',
    rating: 4.9,
    isFavorite: false,
    difficulty: 'Medium',
    servings: 4,
    calories: 380,
    chefName: 'Chef Alex',
    aiTips: 'For extra fluffy pancakes, let the batter rest for 5-10 minutes before cooking. If using frozen blueberries, don\'t thaw them first - add them frozen to prevent bleeding into the batter.',
    prepTimeMinutes: 15,
  ),
  Recipe(
    id: '5',
    title: 'Spicy Black Bean Tacos',
    description: 'These vegetarian tacos are loaded with seasoned black beans, fresh veggies, and a zesty lime crema. A quick and satisfying meal that\'s perfect for busy weeknights!',
    imageUrl: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?q=80&w=1170&auto=format&fit=crop',
    ingredients: [
      {'name': 'Black beans', 'amount': '2', 'unit': 'cans (15 oz each), drained'},
      {'name': 'Olive oil', 'amount': '2', 'unit': 'tbsp'},
      {'name': 'Onion', 'amount': '1', 'unit': 'medium, diced'},
      {'name': 'Garlic', 'amount': '3', 'unit': 'cloves, minced'},
      {'name': 'Cumin', 'amount': '2', 'unit': 'tsp'},
      {'name': 'Chili powder', 'amount': '1', 'unit': 'tbsp'},
      {'name': 'Corn tortillas', 'amount': '12', 'unit': 'small'},
      {'name': 'Sour cream', 'amount': '1', 'unit': 'cup'},
      {'name': 'Lime', 'amount': '1', 'unit': 'juiced and zested'},
      {'name': 'Avocado', 'amount': '2', 'unit': 'sliced'},
      {'name': 'Cilantro', 'amount': '1/2', 'unit': 'cup, chopped'},
      {'name': 'Red cabbage', 'amount': '2', 'unit': 'cups, shredded'},
      {'name': 'Hot sauce', 'amount': '', 'unit': 'to taste'},
    ],
    instructions: [
      'Heat olive oil in a large skillet over medium heat. Add onion and sauté for 5 minutes until softened.',
      'Add garlic and cook for 1 minute until fragrant.',
      'Stir in black beans, cumin, and chili powder. Mash about half the beans with a fork or potato masher.',
      'Cook for 5-7 minutes, stirring occasionally, until mixture is heated through and flavors combine.',
      'Meanwhile, prepare lime crema by mixing sour cream with lime juice and zest.',
      'Warm tortillas according to package directions.',
      'Assemble tacos: add a spoonful of bean mixture to each tortilla, top with shredded cabbage, avocado slices, and cilantro.',
      'Drizzle with lime crema and hot sauce if desired.'
    ],
    totalTimeMinutes: 25,
    category: 'Dinner',
    rating: 4.6,
    isFavorite: true,
    difficulty: 'Easy',
    servings: 4,
    calories: 320,
    chefName: 'Chef Maria',
    aiTips: 'Toast your tortillas on an open flame for 10-15 seconds per side for authentic charred flavor. For meal prep, the bean mixture can be made ahead and refrigerated for up to 3 days.',
    prepTimeMinutes: 15,
  ),
  Recipe(
    id: '6',
    title: 'Lemon Garlic Roasted Salmon',
    description: 'Tender, flaky salmon fillets roasted with a bright lemon garlic butter sauce. This elegant yet simple dish is perfect for both weeknight dinners and special occasions.',
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?q=80&w=1170&auto=format&fit=crop',
    ingredients: [
      {'name': 'Salmon fillets', 'amount': '4', 'unit': '(6 oz each)'},
      {'name': 'Butter', 'amount': '4', 'unit': 'tbsp, melted'},
      {'name': 'Garlic', 'amount': '4', 'unit': 'cloves, minced'},
      {'name': 'Lemon', 'amount': '1', 'unit': 'juiced and zested'},
      {'name': 'Fresh dill', 'amount': '2', 'unit': 'tbsp, chopped'},
      {'name': 'Salt', 'amount': '1', 'unit': 'tsp'},
      {'name': 'Black pepper', 'amount': '1/2', 'unit': 'tsp'},
      {'name': 'Lemon slices', 'amount': '1', 'unit': 'for garnish'},
    ],
    instructions: [
      'Preheat oven to 400°F (200°C). Line a baking sheet with parchment paper or aluminum foil.',
      'In a small bowl, mix melted butter, minced garlic, lemon juice, lemon zest, and dill.',
      'Place salmon fillets on the prepared baking sheet, skin side down. Season with salt and pepper.',
      'Pour the lemon garlic butter mixture evenly over the salmon fillets.',
      'Bake for 12-15 minutes, or until salmon is cooked through and flakes easily with a fork.',
      'Garnish with lemon slices and additional fresh dill if desired.',
      'Serve immediately with your favorite sides.'
    ],
    totalTimeMinutes: 25,
    category: 'Dinner',
    rating: 4.8,
    isFavorite: false,
    difficulty: 'Easy',
    servings: 4,
    calories: 320,
    chefName: 'Chef Daniel',
    aiTips: 'For perfectly cooked salmon, follow the 10-minute rule: cook for 10 minutes per inch of thickness. If you don\'t have fresh dill, you can substitute with dried dill (use 2 teaspoons) or fresh parsley.',
    prepTimeMinutes: 10,
  ),
  Recipe(
    id: '7',
    title: 'Classic Chocolate Chip Cookies',
    description: 'Perfectly chewy in the middle with crisp edges, these classic chocolate chip cookies are a timeless treat everyone will love. They\'re easy to make and absolutely irresistible!',
    imageUrl: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?q=80&w=1170&auto=format&fit=crop',
    ingredients: [
      {'name': 'All-purpose flour', 'amount': '2 1/4', 'unit': 'cups'},
      {'name': 'Baking soda', 'amount': '1', 'unit': 'tsp'},
      {'name': 'Salt', 'amount': '1', 'unit': 'tsp'},
      {'name': 'Unsalted butter', 'amount': '1', 'unit': 'cup, softened'},
      {'name': 'Brown sugar', 'amount': '3/4', 'unit': 'cup, packed'},
      {'name': 'Granulated sugar', 'amount': '3/4', 'unit': 'cup'},
      {'name': 'Vanilla extract', 'amount': '2', 'unit': 'tsp'},
      {'name': 'Eggs', 'amount': '2', 'unit': 'large'},
      {'name': 'Chocolate chips', 'amount': '2', 'unit': 'cups'},
      {'name': 'Walnuts', 'amount': '1', 'unit': 'cup, chopped (optional)'},
    ],
    instructions: [
      'Preheat oven to 375°F (190°C). Line baking sheets with parchment paper.',
      'In a small bowl, whisk together flour, baking soda, and salt.',
      'In a large bowl, beat softened butter, brown sugar, and granulated sugar until creamy.',
      'Add vanilla and eggs to the butter mixture, one at a time, beating well after each addition.',
      'Gradually add flour mixture to wet ingredients and mix until just combined.',
      'Stir in chocolate chips and nuts (if using).',
      'Drop tablespoon-sized balls of dough onto the prepared baking sheets, spacing them about 2 inches apart.',
      'Bake for 9-11 minutes or until golden brown around the edges but still soft in the center.',
      'Let cool on baking sheets for 2 minutes, then transfer to wire racks to cool completely.'
    ],
    totalTimeMinutes: 30,
    category: 'Desserts',
    rating: 4.9,
    isFavorite: true,
    difficulty: 'Medium',
    servings: 36,
    calories: 150,
    chefName: 'Chef Sarah',
    aiTips: 'For extra soft cookies, chill the dough for at least 30 minutes before baking. For a gourmet twist, use a mixture of milk, dark, and white chocolate chips, or try adding a sprinkle of sea salt on top before baking.',
    prepTimeMinutes: 15,
  ),
  Recipe(
    id: '8',
    title: 'Hearty Beef Stew',
    description: 'A comforting classic packed with tender beef, vegetables, and rich savory gravy. This slow-cooked stew is perfect for cold evenings and gets even better the next day!',
    imageUrl: 'https://images.unsplash.com/photo-1608500218890-c4cea7eaec0d?q=80&w=1170&auto=format&fit=crop',
    ingredients: [
      {'name': 'Beef chuck', 'amount': '2', 'unit': 'lbs, cut into 1-inch cubes'},
      {'name': 'All-purpose flour', 'amount': '1/3', 'unit': 'cup'},
      {'name': 'Olive oil', 'amount': '3', 'unit': 'tbsp'},
      {'name': 'Onion', 'amount': '1', 'unit': 'large, chopped'},
      {'name': 'Garlic', 'amount': '4', 'unit': 'cloves, minced'},
      {'name': 'Carrots', 'amount': '4', 'unit': 'medium, sliced'},
      {'name': 'Celery', 'amount': '3', 'unit': 'stalks, sliced'},
      {'name': 'Potatoes', 'amount': '4', 'unit': 'medium, cubed'},
      {'name': 'Beef broth', 'amount': '4', 'unit': 'cups'},
      {'name': 'Tomato paste', 'amount': '2', 'unit': 'tbsp'},
      {'name': 'Worcestershire sauce', 'amount': '1', 'unit': 'tbsp'},
      {'name': 'Bay leaves', 'amount': '2', 'unit': ''},
      {'name': 'Thyme', 'amount': '2', 'unit': 'tsp, dried'},
      {'name': 'Rosemary', 'amount': '1', 'unit': 'tsp, dried'},
      {'name': 'Salt and pepper', 'amount': '', 'unit': 'to taste'},
      {'name': 'Frozen peas', 'amount': '1', 'unit': 'cup'},
    ],
    instructions: [
      'Toss beef cubes with flour, salt, and pepper until evenly coated.',
      'Heat olive oil in a large Dutch oven over medium-high heat. Working in batches, brown the beef on all sides. Transfer to a plate.',
      'In the same pot, add onions and cook until softened, about 3 minutes. Add garlic and cook for 30 seconds more.',
      'Add carrots and celery, cook for 5 minutes, stirring occasionally.',
      'Return beef to the pot. Add potatoes, beef broth, tomato paste, Worcestershire sauce, bay leaves, thyme, and rosemary.',
      'Bring to a boil, then reduce heat to low. Cover and simmer for 2-2.5 hours, until meat is very tender.',
      'Add frozen peas during the last 5 minutes of cooking.',
      'Remove bay leaves, adjust seasoning to taste, and serve hot.'
    ],
    totalTimeMinutes: 180,
    category: 'Dinner',
    rating: 4.8,
    isFavorite: false,
    difficulty: 'Medium',
    servings: 6,
    calories: 420,
    chefName: 'Chef Robert',
    aiTips: 'For extra flavor, deglaze the pan with 1/2 cup of red wine after cooking the vegetables. This stew freezes brilliantly for up to 3 months, so consider making a double batch.',
    prepTimeMinutes: 30,
  ),
  Recipe(
    id: '9',
    title: 'Fresh Mango Salsa',
    description: 'This vibrant salsa combines sweet mango with jalapeño, red onion, and cilantro for a refreshing appetizer. It\'s perfect with tortilla chips or as a topping for grilled fish or tacos!',
    imageUrl: 'https://images.unsplash.com/photo-1600213903598-25be92abde40?q=80&w=1170&auto=format&fit=crop',
    ingredients: [
      {'name': 'Ripe mangoes', 'amount': '2', 'unit': 'large, diced'},
      {'name': 'Red bell pepper', 'amount': '1', 'unit': 'diced'},
      {'name': 'Red onion', 'amount': '1/4', 'unit': 'cup, finely diced'},
      {'name': 'Jalapeño', 'amount': '1', 'unit': 'seeded and minced'},
      {'name': 'Fresh cilantro', 'amount': '1/3', 'unit': 'cup, chopped'},
      {'name': 'Lime juice', 'amount': '2', 'unit': 'tbsp'},
      {'name': 'Salt', 'amount': '1/4', 'unit': 'tsp'},
      {'name': 'Black pepper', 'amount': '1/8', 'unit': 'tsp'},
    ],
    instructions: [
      'Combine diced mango, bell pepper, red onion, and jalapeño in a medium bowl.',
      'Add chopped cilantro, lime juice, salt, and pepper.',
      'Gently toss to combine all ingredients.',
      'For best flavor, refrigerate for at least 1 hour before serving to allow flavors to meld.',
      'Serve with tortilla chips or as a topping for grilled fish or tacos.'
    ],
    totalTimeMinutes: 15,
    category: 'Condiment',
    rating: 4.7,
    isFavorite: true,
    difficulty: 'Easy',
    servings: 6,
    calories: 85,
    chefName: 'Chef Isabella',
    aiTips: 'Choose mangoes that yield slightly to pressure for the perfect ripeness. For a tropical twist, add diced pineapple or a splash of orange juice. Adjust the heat level by adding more or less jalapeño.',
    prepTimeMinutes: 15,
  ),
  Recipe(
    id: '10',
    title: 'Homemade Vegetable Pizza',
    description: 'A delicious pizza topped with a colorful array of fresh vegetables and melty cheese on a homemade crust. Customize with your favorite toppings for a perfect pizza night!',
    imageUrl: 'https://images.unsplash.com/photo-1604917877934-07d8d248d396?q=80&w=1170&auto=format&fit=crop',
    ingredients: [
      {'name': 'Pizza dough', 'amount': '1', 'unit': 'batch (homemade or store-bought)'},
      {'name': 'Pizza sauce', 'amount': '1', 'unit': 'cup'},
      {'name': 'Mozzarella cheese', 'amount': '2', 'unit': 'cups, shredded'},
      {'name': 'Bell peppers', 'amount': '2', 'unit': 'different colors, sliced'},
      {'name': 'Red onion', 'amount': '1/2', 'unit': 'thinly sliced'},
      {'name': 'Mushrooms', 'amount': '1', 'unit': 'cup, sliced'},
      {'name': 'Cherry tomatoes', 'amount': '1', 'unit': 'cup, halved'},
      {'name': 'Black olives', 'amount': '1/4', 'unit': 'cup, sliced'},
      {'name': 'Fresh basil', 'amount': '1/4', 'unit': 'cup, torn'},
      {'name': 'Dried oregano', 'amount': '1', 'unit': 'tsp'},
      {'name': 'Olive oil', 'amount': '1', 'unit': 'tbsp'},
      {'name': 'Cornmeal', 'amount': '2', 'unit': 'tbsp (for dusting)'},
    ],
    instructions: [
      'Preheat oven to 475°F (245°C). If using a pizza stone, place it in the oven while preheating.',
      'Roll out pizza dough on a floured surface to your desired thickness.',
      'Sprinkle a pizza peel or inverted baking sheet with cornmeal and transfer dough onto it.',
      'Spread pizza sauce evenly over dough, leaving a small border for the crust.',
      'Sprinkle half of the cheese over the sauce.',
      'Arrange vegetables on top and sprinkle with remaining cheese and oregano.',
      'Drizzle with olive oil and carefully transfer to the preheated oven or pizza stone.',
      'Bake for 12-15 minutes until crust is golden and cheese is bubbly.',
      'Top with fresh basil leaves before serving.'
    ],
    totalTimeMinutes: 40,
    category: 'Dinner',
    rating: 4.6,
    isFavorite: false,
    difficulty: 'Medium',
    servings: 4,
    calories: 350,
    chefName: 'Chef Marco',
    aiTips: 'For a crispier crust, preheat your baking sheet or pizza stone for at least 30 minutes. To prevent a soggy center, lightly sauté vegetables with high water content like mushrooms before adding them as toppings.',
    prepTimeMinutes: 25,
  ),
  Recipe(
    id: '11',
    title: 'Banana Protein Smoothie',
    description: 'Start your day with this creamy, nutritious smoothie packed with protein, potassium, and flavor. Perfect for a quick breakfast or post-workout refuel!',
    imageUrl: 'https://images.unsplash.com/photo-1553530666-ba11a90a0875?q=80&w=1170&auto=format&fit=crop',
    ingredients: [
      {'name': 'Ripe banana', 'amount': '1', 'unit': 'medium, frozen'},
      {'name': 'Greek yogurt', 'amount': '1/2', 'unit': 'cup'},
      {'name': 'Milk', 'amount': '1', 'unit': 'cup (dairy or plant-based)'},
      {'name': 'Protein powder', 'amount': '1', 'unit': 'scoop'},
      {'name': 'Peanut butter', 'amount': '1', 'unit': 'tbsp'},
      {'name': 'Honey', 'amount': '1', 'unit': 'tsp (optional)'},
      {'name': 'Cinnamon', 'amount': '1/4', 'unit': 'tsp'},
      {'name': 'Ice cubes', 'amount': '4-5', 'unit': '(optional)'},
    ],
    instructions: [
      'Place all ingredients in a blender in the order listed.',
      'Blend on high speed until smooth and creamy, about 1 minute.',
      'If smoothie is too thick, add more milk; if too thin, add more ice or frozen banana.',
      'Taste and adjust sweetness if needed.',
      'Pour into a glass and enjoy immediately.'
    ],
    totalTimeMinutes: 5,
    category: 'Breakfast',
    rating: 4.5,
    isFavorite: true,
    difficulty: 'Easy',
    servings: 1,
    calories: 310,
    chefName: 'Chef Olivia',
    aiTips: 'For extra nutrients, add a handful of spinach - you won\'t taste it! Freeze peeled banana chunks ahead of time for the perfect smoothie texture without watering it down with ice.',
    prepTimeMinutes: 5,
  ),
  Recipe(
    id: '12',
    title: 'Perfect Guacamole',
    description: 'This authentic guacamole recipe features ripe avocados, lime, cilantro, and just the right amount of spice. It\'s a crowd-pleasing dip that disappears fast!',
    imageUrl: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?q=80&w=984&auto=format&fit=crop',
    ingredients: [
      {'name': 'Ripe avocados', 'amount': '3', 'unit': 'large'},
      {'name': 'Lime', 'amount': '1', 'unit': 'juiced'},
      {'name': 'Red onion', 'amount': '1/4', 'unit': 'cup, finely diced'},
      {'name': 'Cilantro', 'amount': '1/4', 'unit': 'cup, chopped'},
      {'name': 'Jalapeño', 'amount': '1', 'unit': 'seeded and minced'},
      {'name': 'Garlic', 'amount': '1', 'unit': 'clove, minced'},
      {'name': 'Salt', 'amount': '1/2', 'unit': 'tsp'},
      {'name': 'Tomato', 'amount': '1', 'unit': 'medium, diced (optional)'},
      {'name': 'Ground cumin', 'amount': '1/8', 'unit': 'tsp (optional)'},
    ],
    instructions: [
      'Cut avocados in half, remove pits, and scoop flesh into a medium bowl.',
      'Mash avocados with a fork, leaving some chunks for texture.',
      'Add lime juice and mix gently to combine (this prevents browning).',
      'Stir in red onion, cilantro, jalapeño, garlic, and salt. Add tomato and cumin if using.',
      'Taste and adjust seasoning as needed.',
      'Serve immediately with tortilla chips, or place plastic wrap directly on the surface of the guacamole and refrigerate up to 2 hours.'
    ],
    totalTimeMinutes: 15,
    category: 'Condiment',
    rating: 4.9,
    isFavorite: true,
    difficulty: 'Easy',
    servings: 6,
    calories: 170,
    chefName: 'Chef Carlos',
    aiTips: 'To check if an avocado is ripe, gently press near the stem - it should yield slightly. Keep the pit in any leftover guacamole to help prevent browning, along with the plastic wrap trick.',
    prepTimeMinutes: 15,
  ),
];