import '../models/ingredient.dart';

final List<Ingredient> dummyIngredients = [
  const Ingredient(
    id: 'ing1',
    name: 'Organic Chicken Breast',
    quantity: '2',
    unit: 'lbs',
    category: 'Meat & Seafood',
    recipeId: '2',
    isPurchased: false,
  ),
  const Ingredient(
    id: 'ing2',
    name: 'Extra Virgin Olive Oil',
    quantity: '1',
    unit: 'bottle',
    category: 'Condiment',
    isPurchased: true,
  ),
  const Ingredient(
    id: 'ing3',
    name: 'Fresh Spinach',
    quantity: '1',
    unit: 'bag',
    category: 'Produce',
    isPurchased: false,
  ),
  const Ingredient(
    id: 'ing4',
    name: 'Garlic',
    quantity: '1',
    unit: 'head',
    category: 'Produce',
    isPurchased: false,
  ),
  const Ingredient(
    id: 'ing5',
    name: 'Red Onions',
    quantity: '3',
    unit: '',
    category: 'Produce',
    isPurchased: true,
  ),
  const Ingredient(
    id: 'ing6',
    name: 'Whole Wheat Pasta',
    quantity: '2',
    unit: 'boxes',
    category: 'Grains & Bread',
    recipeId: '1',
    isPurchased: false,
  ),
  const Ingredient(
    id: 'ing7',
    name: 'Parmesan Cheese',
    quantity: '8',
    unit: 'oz',
    category: 'Dairy',
    recipeId: '1',
    isPurchased: true,
  ),
  const Ingredient(
    id: 'ing8',
    name: 'Greek Yogurt',
    quantity: '32',
    unit: 'oz',
    category: 'Dairy',
    isPurchased: false,
  ),
  const Ingredient(
    id: 'ing9',
    name: 'Avocados',
    quantity: '4',
    unit: 'ripe',
    category: 'Produce',
    recipeId: '12',
    isPurchased: false,
  ),
  const Ingredient(
    id: 'ing10',
    name: 'Tomatoes',
    quantity: '6',
    unit: 'medium',
    category: 'Produce',
    isPurchased: true,
  ),
  const Ingredient(
    id: 'ing11',
    name: 'Brown Rice',
    quantity: '1',
    unit: 'bag',
    category: 'Grains & Bread',
    isPurchased: false,
  ),
  const Ingredient(
    id: 'ing12',
    name: 'Salmon Fillets',
    quantity: '1',
    unit: 'lb',
    category: 'Meat & Seafood',
    recipeId: '6',
    isPurchased: false,
  ),
  const Ingredient(
    id: 'ing13',
    name: 'Black Beans',
    quantity: '2',
    unit: 'cans',
    category: 'Canned Goods',
    recipeId: '5',
    isPurchased: true,
  ),
  const Ingredient(
    id: 'ing14',
    name: 'Cumin',
    quantity: '1',
    unit: 'bottle',
    category: 'Spices',
    isPurchased: false,
  ),
  const Ingredient(
    id: 'ing15',
    name: 'Limes',
    quantity: '5',
    unit: '',
    category: 'Produce',
    recipeId: '12',
    isPurchased: false,
  ),
  const Ingredient(
    id: 'ing16',
    name: 'Honey',
    quantity: '1',
    unit: 'bottle',
    category: 'Baking',
    isPurchased: true,
  ),
  const Ingredient(
    id: 'ing17',
    name: 'Chocolate Chips',
    quantity: '1',
    unit: 'bag',
    category: 'Baking',
    recipeId: '7',
    isPurchased: false,
  ),
  const Ingredient(
    id: 'ing18',
    name: 'Frozen Blueberries',
    quantity: '2',
    unit: 'bags',
    category: 'Frozen',
    recipeId: '4',
    isPurchased: true,
  ),
  const Ingredient(
    id: 'ing19',
    name: 'Almond Milk',
    quantity: '1',
    unit: 'half gallon',
    category: 'Dairy',
    isPurchased: false,
  ),
  const Ingredient(
    id: 'ing20',
    name: 'Bell Peppers',
    quantity: '3',
    unit: 'assorted colors',
    category: 'Produce',
    recipeId: '5',
    isPurchased: false,
  ),
  const Ingredient(
    id: 'ing21',
    name: 'Protein Powder',
    quantity: '1',
    unit: 'container',
    category: 'Other',
    recipeId: '11',
    isPurchased: true,
  ),
  const Ingredient(
    id: 'ing22',
    name: 'Peanut Butter',
    quantity: '1',
    unit: 'jar',
    category: 'Condiment',
    recipeId: '11',
    isPurchased: false,
  ),
];