name: cookmateai
description: "A new Flutter project."
publish_to: "none"

version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.1 # HTTP client for API calls

  # Core packages
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.10
  go_router: ^13.2.0
  http: ^1.1.0
  shared_preferences: ^2.2.2

  # UI and Animation
  animations: ^2.0.8
  animate_do: ^3.3.0
  lottie: ^3.1.0
  dotlottie_loader: ^0.0.5

  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  share_plus: ^7.2.1
  flutter_hooks: ^0.20.3
  carousel_slider: ^4.2.1
  flutter_form_builder: ^9.1.1
  flutter_neumorphic: ^3.0.3
  flutter_slidable: ^3.0.1
  google_fonts: ^6.1.0

  # State Management
  hooks_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.3

  # AI Integration
  google_generative_ai: ^0.2.2

  flutter_gemini: ^2.0.1

  # Speech and Voice Processing
  speech_to_text: ^7.0.0
  flutter_tts: ^3.8.5
  vad: ^0.0.5
  web_socket_channel: ^2.4.0  # For Deepgram WebSocket communication
  record: ^5.0.1  # For audio recording
  
  # Timer Feature
  flutter_local_notifications: ^19.1.0
  rxdart: ^0.27.7  # For stream-based timer management

  # Camera and Image Processing
  camera: ^0.10.5+9
  image: ^4.1.3
  google_mlkit_commons: ^0.6.1
  google_mlkit_image_labeling: ^0.10.0

  # Utilities
  intl: ^0.19.0
  uuid: ^4.3.3
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  flutter_dotenv: ^5.1.0
  just_audio: ^0.9.46
  video_player: ^2.9.5

  image_picker: ^1.0.4
  form_builder_validators: ^11.0.0 
  sqflite: ^2.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/animations/

    - assets/mov/
    - assets/
