name: cook_mate_ai
description: "A cooking assistant app with AI features."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0-323.0.dev

dependencies:
  flutter:
    sdk: flutter
  
  # Core packages
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.10
  go_router: ^13.2.0
  http: ^1.2.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  # Uncomment to add assets
  # assets:
  #   - assets/images/
