name: cookmateai
description: "A new Flutter project."
publish_to: "none"

version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.1 # HTTP client for API calls

  # Core packages
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.10
  go_router: ^13.2.0
  http: ^1.1.0
  shared_preferences: ^2.2.2

  # UI and Animation
  animations: ^2.0.8
  animate_do: ^3.3.0
  lottie: ^3.1.0
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  share_plus: ^7.2.1
  flutter_hooks: ^0.20.3
  carousel_slider: ^4.2.1
  flutter_form_builder: ^9.1.1
  flutter_neumorphic: ^3.0.3

  # State Management
  hooks_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.3

  # AI Integration
  google_generative_ai: ^0.2.2

  # Utilities
  intl: ^0.19.0
  uuid: ^4.2.2
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  form_builder_validators: ^11.0.0 # Updated version
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  # Uncomment these lines once you've created the asset directories
  # assets:
  #   - assets/images/
  #   - assets/animations/
