name: cook_mate_ai
description: "A cooking assistant app with AI features."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

#environment:
#  sdk: ^3.5.0-323.0.dev

environment:
  sdk: ">=3.5.0-180.3.beta <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core packages
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.10
  go_router: ^13.2.0
  http: ^1.2.1
  shared_preferences: ^2.2.2

  # UI and Animation
  animations: ^2.0.8
  animate_do: ^3.0.2
  lottie: ^3.1.0
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  share_plus: ^7.2.1
  flutter_hooks: ^0.20.3
  carousel_slider: ^4.2.1
  flutter_form_builder: ^9.3.0
  flutter_neumorphic: ^3.0.3

  # State Management
  hooks_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.3

  # AI Integration
  google_generative_ai: ^0.2.2

  # Utilities
  intl: ^0.19.0
  uuid: ^4.0.0
  path_provider: ^2.1.2
  image_picker: ^1.1.2
  form_builder_validators: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/
